"""加入用户权限控制

Revision ID: 659428dcfe9b
Revises: eebcff4e6c33
Create Date: 2020-02-03 21:35:49.852965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659428dcfe9b'
down_revision = 'eebcff4e6c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_user', 't_role', ['kind'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    # ### end Alembic commands ###
