"""更新时间的默认字段

Revision ID: ce8f55cb539b
Revises: fe334b260916
Create Date: 2020-02-03 18:32:26.311358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8f55cb539b'
down_revision = 'fe334b260916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_lost_found', 't_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_lost_found', type_='foreignkey')
    # ### end Alembic commands ###
