"""empty message

Revision ID: fa49c4d357a0
Revises: 7e0c25aeb106
Create Date: 2020-01-28 20:43:11.468466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa49c4d357a0'
down_revision = '7e0c25aeb106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_feedback', sa.Column('handler_id', sa.Integer(), nullable=False))
    op.add_column('t_feedback', sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_foreign_key(None, 't_feedback', 't_user', ['handler_id'], ['id'])
    op.drop_column('t_feedback', 'real_name')
    op.drop_column('t_feedback', 'username')
    op.drop_column('t_feedback', 'record_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_feedback', sa.Column('record_status', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('t_feedback', sa.Column('username', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('t_feedback', sa.Column('real_name', mysql.VARCHAR(length=256), nullable=False))
    op.drop_constraint(None, 't_feedback', type_='foreignkey')
    op.drop_column('t_feedback', 'status')
    op.drop_column('t_feedback', 'handler_id')
    # ### end Alembic commands ###
