"""测试

Revision ID: 0157c3f72f30
Revises: fde2eac18778
Create Date: 2020-03-14 22:03:02.561305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0157c3f72f30'
down_revision = 'fde2eac18778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_feedback_ibfk_2', 't_feedback', type_='foreignkey')
    op.drop_constraint('t_feedback_ibfk_1', 't_feedback', type_='foreignkey')
    op.create_foreign_key(None, 't_feedback', 't_user', ['handler_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 't_feedback', 't_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('t_report', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 't_report', 't_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_report', type_='foreignkey')
    op.alter_column('t_report', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 't_feedback', type_='foreignkey')
    op.drop_constraint(None, 't_feedback', type_='foreignkey')
    op.create_foreign_key('t_feedback_ibfk_1', 't_feedback', 't_user', ['handler_id'], ['id'])
    op.create_foreign_key('t_feedback_ibfk_2', 't_feedback', 't_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
