"""删除目录以及通知表中的user_id字段

Revision ID: 09ab9d49b858
Revises: 2795f6ec3f3d
Create Date: 2020-02-05 20:41:48.862036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09ab9d49b858'
down_revision = '2795f6ec3f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_category_ibfk_1', 't_category', type_='foreignkey')
    op.drop_column('t_category', 'user_id')
    op.drop_constraint('t_notice_ibfk_1', 't_notice', type_='foreignkey')
    op.drop_column('t_notice', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_notice', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('t_notice_ibfk_1', 't_notice', 't_user', ['user_id'], ['id'])
    op.add_column('t_category', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('t_category_ibfk_1', 't_category', 't_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
