"""增加表情包支持

Revision ID: 5e7a4b17631f
Revises: b496846efcd7
Create Date: 2020-03-21 13:05:28.482789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7a4b17631f'
down_revision = 'b496846efcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('fix_top', sa.Enum('0', '1', name='kind_enum'), server_default=sa.text('0'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_notice')
    # ### end Alembic commands ###
