"""更改字段长度

Revision ID: 5ed094f55ff5
Revises: 4d2397899132
Create Date: 2020-03-22 21:02:48.497522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ed094f55ff5'
down_revision = '4d2397899132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openid', 'qq_id',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=35),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openid', 'qq_id',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
