"""更改字段长度

Revision ID: 78c5821abb74
Revises: 5ed094f55ff5
Create Date: 2020-03-22 21:04:22.001376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78c5821abb74'
down_revision = '5ed094f55ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openid', 'qq_id',
               existing_type=mysql.VARCHAR(length=35),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('t_category', 'about',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('t_category', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_category', 'name',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('t_category', 'about',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('openid', 'qq_id',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=35),
               existing_nullable=True)
    # ### end Alembic commands ###
