"""新增OpenID类

Revision ID: 7ae8e4505c0f
Revises: ea6dcb712565
Create Date: 2020-02-08 19:03:20.805094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ae8e4505c0f'
down_revision = 'ea6dcb712565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq_id', sa.String(length=20), nullable=True),
    sa.Column('wx_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qq_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('wx_id')
    )
    op.drop_index('qq_id', table_name='openid')
    op.drop_index('user_id', table_name='openid')
    op.drop_index('wx_id', table_name='openid')
    op.drop_table('openid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openid',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('qq_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('wx_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], name='openid_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('wx_id', 'openid', ['wx_id'], unique=True)
    op.create_index('user_id', 'openid', ['user_id'], unique=True)
    op.create_index('qq_id', 'openid', ['qq_id'], unique=True)
    op.drop_table('openID')
    # ### end Alembic commands ###
