"""更改文件字段的长度

Revision ID: 8b43476bb761
Revises: d626516a2878
Create Date: 2020-02-28 13:35:20.259448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b43476bb761'
down_revision = 'd626516a2878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_report', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_report', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
