"""加入文件支持

Revision ID: d626516a2878
Revises: 324d6e6280e2
Create Date: 2020-02-27 20:57:30.661276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd626516a2878'
down_revision = '324d6e6280e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_report',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'openid', ['qq_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'openid', type_='unique')
    op.drop_table('t_report')
    # ### end Alembic commands ###
