"""新增OpenID类

Revision ID: ea6dcb712565
Revises: 09ab9d49b858
Create Date: 2020-02-08 19:00:10.518911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea6dcb712565'
down_revision = '09ab9d49b858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq_id', sa.String(length=20), nullable=True),
    sa.Column('wx_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qq_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('wx_id')
    )
    op.alter_column('t_user', 'gender',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_user', 'kind',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'kind',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('t_user', 'gender',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_table('openID')
    # ### end Alembic commands ###
