"""增加外键

Revision ID: fde2eac18778
Revises: 9fcb9083f383
Create Date: 2020-02-29 22:09:35.945657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde2eac18778'
down_revision = '9fcb9083f383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_feedback', 't_user', ['handler_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_feedback', type_='foreignkey')
    # ### end Alembic commands ###
