FLASK_RUN_HOST = 0.0.0.0
FLASK_RUN_PORT = 8888
FLASK_ENV  = development
#FLASK_ENV = production
FLASK_DEBUG = False
PIPENV_DONT_LOAD_ENV = 1
DEBUG_TB_INTERCEPT_REDIRECTS  =  False
DEBUG_TB_INTERCEPT_REDIRECTS  =  False
PATH_OF_UPLOAD = 'app/static/upload/'
SITE_URL='http://iboy.f3322.net:8888/'
C_FORCE_ROOT=True

