FLASK_RUN_HOST=127.0.0.1
FLASK_RUN_PORT=80
FLASK_ENV= development
FLASK_DEBUG=True
FLASK_APP=setup.py
PIPENV_DONT_LOAD_ENV=1
MXA_ATTEMPT_NUMBER=5
FlASK_CONFIG=development
#DebugToolbar会拦截重定向请求
DEBUG_TB_INTERCEPT_REDIRECTS = False
