FLASK_RUN_HOST = 0.0.0.0
FLASK_RUN_PORT = 8888
FLASK_ENV =  development
FLASK_DEBUG = True
FLASK_APP = app:create_app('development')
PIPENV_DONT_LOAD_ENV = 1
FlASK_CONFIG = development
DEBUG_TB_INTERCEPT_REDIRECTS  =  False
DEBUG_TB_INTERCEPT_REDIRECTS  =  False
PATH_OF_IMAGES_DIR = 'app/static/upload'

