version: '2'
services:
  # PythonWeb服务
  flask:
    # build: .
    image: registry.cn-hangzhou.aliyuncs.com/ctgu/swzl:latest
    container_name: flask
#    ports:
#      - 8888:8888
    # working_dir: /www/wwwroot/ctguswzl.cn
    volumes: # 文件夹映射
      - ./:/www/wwwroot/ctguswzl.cn # 挂载源码
      - /etc/timezone:/etc/timezone #同步时区
      - /etc/localtime:/etc/localtime #同步时区
#    command: /bin/sh -c "cd /www/wwwroot/ctguswzl.cn  && ./boot.sh && ./celery.sh "
    privileged: true
    depends_on:
      - redis
      - mysql
    env_file:
      - ./.env
      - ./.flaskenv
    restart: always
    networks:
      - net

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /www/server/mysql/data:/var/lib/mysql # 挂载数据目录
      - /www/server/mysql/conf:/etc/mysql/conf.d # 挂载配置文件目录
      - /www/server/mysql/logs:/var/log/mysql:rw # 挂载配置文件目录
      - /www/server/mysql/init:/docker-entrypoint-initdb.d:ro
    privileged: true
    env_file:
      - /www/server/mysql/mysql.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - net

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /www/server/redis/data:/data
      - /www/server/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone #同步时区
      - /etc/localtime:/etc/localtime #同步时区
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - net

  nginx:
    image:  registry.cn-hangzhou.aliyuncs.com/ctgu/nginx-lua-alpine:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www/server/nginx/proxy:/etc/nginx/proxy #反向代理配置文件
      - /www/server/nginx/cert:/etc/nginx/cert #证书文件
      - /www/server/nginx/conf.d:/etc/nginx/conf.d # nginx站点配置文件
      - /www/wwwroot:/etc/nginx/sites-available # 宿主:docker:只读  ,www目录
#      - /www/server/nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf # nginx配置文件
      - /www/server/nginx/conf/nginx.conf:/etc/nginx/nginx.conf # nginx配置文件
      - /www/server/nginx/logs:/etc/nginx/logs # 网站日志文件
      - /www/server/nginx/waf:/etc/nginx/waf # 网站防火墙
      - /www/wwwroot:/www/wwwroot
      - /etc/timezone:/etc/timezone #同步时区
      - /etc/localtime:/etc/localtime #同步时区
    depends_on:
      - flask
    restart: always
    networks:
      - net
networks:
  net:
    driver: bridge
