FLASK_RUN_HOST=地址
FLASK_RUN_PORT=端口
FLASK_ENV=环境
#FLASK_ENV=production
#FLASK_ENV=testing
FLASK_DEBUG=False
PIPENV_DONT_LOAD_ENV=1
DEBUG_TB_INTERCEPT_REDIRECTS=False
DEBUG_TB_INTERCEPT_REDIRECTS=False
#图片上传路径
PATH_OF_UPLOAD=app/static/upload/
MINI_IMG_PATH=app/static/thumb/
#报表生成路径
PATH_OF_REPORT=app/static/file/
#报表模板路径
PATH_OF_TEMP=app/static/temp/
#站点地址
SITE_URL=http://www.example.com/
#CDN加速地址
CDN_URL=http://www.example.com
C_FORCE_ROOT=True

