"""更改部分字段长度

Revision ID: 0171adcde9b8
Revises: f3f461303621
Create Date: 2020-03-22 21:35:19.335745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0171adcde9b8'
down_revision = 'f3f461303621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_comment', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=1024),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('t_feedback', 'answer',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=1024),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('t_feedback', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=1024),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('t_feedback', 'subject',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=256),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('t_lost_found', 'about',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=1024),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.alter_column('t_lost_found', 'images',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('t_lost_found', 'location',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('t_lost_found', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=128),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('t_notice', 'content',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=1024),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('t_notice', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', length=128),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('t_permission', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('t_report', 'file_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('t_report', 'id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50))
    op.create_unique_constraint(None, 't_report', ['id'])
    op.alter_column('t_user', 'class_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=35),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('t_user', 'username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('t_user', 'class_name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 't_report', type_='unique')
    op.alter_column('t_report', 'id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100))
    op.alter_column('t_report', 'file_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('t_permission', 'name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('t_notice', 'title',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(charset='utf8mb4', length=128),
               existing_nullable=False)
    op.alter_column('t_notice', 'content',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(charset='utf8mb4', length=1024),
               existing_nullable=False)
    op.alter_column('t_lost_found', 'title',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(charset='utf8mb4', length=128),
               existing_nullable=False)
    op.alter_column('t_lost_found', 'location',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('t_lost_found', 'images',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('t_lost_found', 'about',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(charset='utf8mb4', length=1024),
               existing_nullable=False)
    op.alter_column('t_feedback', 'subject',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb4', length=256),
               existing_nullable=False)
    op.alter_column('t_feedback', 'content',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(charset='utf8mb4', length=1024),
               existing_nullable=False)
    op.alter_column('t_feedback', 'answer',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(charset='utf8mb4', length=1024),
               existing_nullable=True)
    op.alter_column('t_comment', 'content',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
