"""测试初始化数据库

Revision ID: 086578b65777
Revises: 
Create Date: 2020-03-23 21:41:08.592615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086578b65777'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('about', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_category_name'), 't_category', ['name'], unique=True)
    op.create_table('t_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('fix_top', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], )
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('real_name', sa.String(length=30), nullable=False),
    sa.Column('academy', sa.String(length=150), nullable=False),
    sa.Column('class_name', sa.String(length=15), nullable=False),
    sa.Column('major', sa.String(length=35), nullable=False),
    sa.Column('qq', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('gender', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kind'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_user_qq'), 't_user', ['qq'], unique=True)
    op.create_index(op.f('ix_t_user_real_name'), 't_user', ['real_name'], unique=False)
    op.create_index(op.f('ix_t_user_username'), 't_user', ['username'], unique=True)
    op.create_table('openid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qq_id', sa.String(length=40), nullable=True),
    sa.Column('wx_id', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qq_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_openid_wx_id'), 'openid', ['wx_id'], unique=True)
    op.create_table('t_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=300), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('handler_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_t_feedback_user_id'), 't_feedback', ['user_id'], unique=False)
    op.create_table('t_lost_found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=400), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('images', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('deal_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('look_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['t_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_t_lost_found_category_id'), 't_lost_found', ['category_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_claimant_id'), 't_lost_found', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_create_time'), 't_lost_found', ['create_time'], unique=False)
    op.create_index(op.f('ix_t_lost_found_title'), 't_lost_found', ['title'], unique=False)
    op.create_index(op.f('ix_t_lost_found_user_id'), 't_lost_found', ['user_id'], unique=False)
    op.create_table('t_report',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_t_report_user_id'), 't_report', ['user_id'], unique=False)
    op.create_table('t_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_found_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lost_found_id'], ['t_lost_found.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_t_comment_lost_found_id'), 't_comment', ['lost_found_id'], unique=False)
    op.create_index(op.f('ix_t_comment_user_id'), 't_comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_comment_user_id'), table_name='t_comment')
    op.drop_index(op.f('ix_t_comment_lost_found_id'), table_name='t_comment')
    op.drop_table('t_comment')
    op.drop_index(op.f('ix_t_report_user_id'), table_name='t_report')
    op.drop_table('t_report')
    op.drop_index(op.f('ix_t_lost_found_user_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_title'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_create_time'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_claimant_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_category_id'), table_name='t_lost_found')
    op.drop_table('t_lost_found')
    op.drop_index(op.f('ix_t_feedback_user_id'), table_name='t_feedback')
    op.drop_table('t_feedback')
    op.drop_index(op.f('ix_openid_wx_id'), table_name='openid')
    op.drop_table('openid')
    op.drop_index(op.f('ix_t_user_username'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_real_name'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_qq'), table_name='t_user')
    op.drop_table('t_user')
    op.drop_table('roles_permissions')
    op.drop_table('t_role')
    op.drop_table('t_permission')
    op.drop_table('t_notice')
    op.drop_index(op.f('ix_t_category_name'), table_name='t_category')
    op.drop_table('t_category')
    # ### end Alembic commands ###
