"""empty message

Revision ID: 2795f6ec3f3d
Revises: 
Create Date: 2020-02-03 23:00:42.778023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2795f6ec3f3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], )
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('academy', sa.String(length=150), nullable=False),
    sa.Column('class_name', sa.String(length=30), nullable=False),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.Column('qq', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('gender', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kind'], ['t_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qq'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('about', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=1024), nullable=True),
    sa.Column('handler_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['handler_id'], ['t_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('fix_top', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_lost_found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('deal_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('look_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['t_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('INDEX_LF', 't_lost_found', ['title', 'category_id'], unique=False)
    op.create_table('t_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_found_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lost_found_id'], ['t_lost_found.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_comment_lost_found_id'), 't_comment', ['lost_found_id'], unique=False)
    op.create_index(op.f('ix_t_comment_user_id'), 't_comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_comment_user_id'), table_name='t_comment')
    op.drop_index(op.f('ix_t_comment_lost_found_id'), table_name='t_comment')
    op.drop_table('t_comment')
    op.drop_index('INDEX_LF', table_name='t_lost_found')
    op.drop_table('t_lost_found')
    op.drop_table('t_notice')
    op.drop_table('t_feedback')
    op.drop_table('t_category')
    op.drop_table('t_user')
    op.drop_table('roles_permissions')
    op.drop_table('t_role')
    op.drop_table('t_permission')
    # ### end Alembic commands ###
