"""增加表情包支持

Revision ID: 393b0a79dfc0
Revises: bebaec67b65e
Create Date: 2020-03-21 13:47:10.409803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b0a79dfc0'
down_revision = 'bebaec67b65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_t_lost_found_category_id'), 't_lost_found', ['category_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_claimant_id'), 't_lost_found', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_create_time'), 't_lost_found', ['create_time'], unique=False)
    op.create_index(op.f('ix_t_lost_found_title'), 't_lost_found', ['title'], unique=False)
    op.create_index(op.f('ix_t_lost_found_user_id'), 't_lost_found', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_lost_found_user_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_title'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_create_time'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_claimant_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_category_id'), table_name='t_lost_found')
    # ### end Alembic commands ###
