"""初始化迁移

Revision ID: 4460f753b4b3
Revises: 
Create Date: 2020-01-22 21:19:40.411891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4460f753b4b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('UNIQUE_USER', table_name='t_user')
    op.drop_table('t_user')
    op.drop_index('UNIQUE_MANAGER', table_name='t_manager')
    op.drop_table('t_manager')
    op.drop_table('t_category')
    op.drop_index('INDEX_LF', table_name='t_lost_found')
    op.drop_table('t_lost_found')
    op.drop_table('t_feedback')
    op.drop_table('t_notice')
    op.drop_index('INDEX_CMT_LF', table_name='t_comment')
    op.drop_index('INDEX_CMT_U', table_name='t_comment')
    op.drop_table('t_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_comment',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('lost_found_id', mysql.VARCHAR(length=64), nullable=False, comment='?????'),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='???ID'),
    sa.Column('content', mysql.VARCHAR(length=128), nullable=False, comment='??'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='????'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('INDEX_CMT_U', 't_comment', ['user_id'], unique=False)
    op.create_index('INDEX_CMT_LF', 't_comment', ['lost_found_id'], unique=False)
    op.create_table('t_notice',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False, comment='????'),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False, comment='????'),
    sa.Column('fix_top', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='????'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='????'),
    sa.Column('creator_id', mysql.VARCHAR(length=64), nullable=False, comment='???ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_feedback',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('answer', mysql.VARCHAR(length=1024), nullable=True, comment='?????'),
    sa.Column('content', mysql.VARCHAR(length=1024), nullable=False, comment='?????'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='????'),
    sa.Column('handler_name', mysql.VARCHAR(length=256), nullable=True, comment='??????'),
    sa.Column('real_name', mysql.VARCHAR(length=256), nullable=False, comment='????????'),
    sa.Column('record_status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='????0/1 0????'),
    sa.Column('subject', mysql.VARCHAR(length=256), nullable=False, comment='?????'),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='???ID'),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False, comment='?????'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_lost_found',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('kind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='?????????'),
    sa.Column('category_id', mysql.VARCHAR(length=128), nullable=False, comment='?????'),
    sa.Column('about', mysql.VARCHAR(length=512), nullable=False, comment='????'),
    sa.Column('title', mysql.VARCHAR(length=128), nullable=False, comment='?????'),
    sa.Column('images', mysql.VARCHAR(length=1024), nullable=True, comment='?????'),
    sa.Column('claimant_id', mysql.VARCHAR(length=64), nullable=True, comment='???ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='????'),
    sa.Column('deal_time', mysql.DATETIME(), nullable=True, comment='?????'),
    sa.Column('fix_top', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='????'),
    sa.Column('location', mysql.VARCHAR(length=512), nullable=True, comment='????'),
    sa.Column('look_count', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('record_status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='??????????0??1??'),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='???id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('INDEX_LF', 't_lost_found', ['title', 'category_id'], unique=False)
    op.create_table('t_category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='???ID'),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False, comment='?????'),
    sa.Column('about', mysql.VARCHAR(length=256), nullable=True, comment='?????'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='???????'),
    sa.Column('user_id', mysql.VARCHAR(length=256), nullable=False, comment='???id'),
    sa.PrimaryKeyConstraint('id', 'name'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_manager',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('creator_id', mysql.DATETIME(), nullable=False),
    sa.Column('qq', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='??ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('UNIQUE_MANAGER', 't_manager', ['user_id'], unique=True)
    op.create_table('t_user',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False, comment='?????'),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False, comment='??'),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False, comment='????'),
    sa.Column('real_name', mysql.VARCHAR(length=256), nullable=False, comment='????'),
    sa.Column('academy', mysql.VARCHAR(length=128), nullable=False, comment='??'),
    sa.Column('class_id', mysql.VARCHAR(length=128), nullable=False, comment='??'),
    sa.Column('major', mysql.VARCHAR(length=30), nullable=False, comment='??'),
    sa.Column('qq', mysql.VARCHAR(length=16), nullable=False, comment='QQ?'),
    sa.Column('avatar', mysql.VARCHAR(length=256), nullable=True, comment='??'),
    sa.Column('kind', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='??/0????/2???/1??????'),
    sa.Column('sex', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='??,0???,1???'),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='????'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='??????'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('UNIQUE_USER', 't_user', ['username', 'qq'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
