"""更改字段长度

Revision ID: 4d2397899132
Revises: 90504143ccfd
Create Date: 2020-03-22 21:01:46.395397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d2397899132'
down_revision = '90504143ccfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_lost_found', 'images',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=800),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_lost_found', 'images',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
