"""更改字段长度

Revision ID: 5433fbe02f86
Revises: fb0020431e02
Create Date: 2020-03-22 21:24:23.038007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5433fbe02f86'
down_revision = 'fb0020431e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_feedback', 'answer',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('t_report', 'id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50))
    op.create_unique_constraint(None, 't_report', ['id'])
    op.alter_column('t_user', 'class_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=35),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('t_user', 'username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('t_user', 'class_name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 't_report', type_='unique')
    op.alter_column('t_report', 'id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100))
    op.alter_column('t_feedback', 'answer',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
