"""更改文件字段的长度

Revision ID: 5cb5a241c91f
Revises: 8b43476bb761
Create Date: 2020-02-28 13:36:15.842559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb5a241c91f'
down_revision = '8b43476bb761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_report', sa.Column('create_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_report', 'create_time')
    # ### end Alembic commands ###
