"""增加用户状态字段

Revision ID: 7a988f55ee48
Revises: 6a14caf8b438
Create Date: 2020-01-29 12:06:40.326427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a988f55ee48'
down_revision = '6a14caf8b438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'status')
    # ### end Alembic commands ###
