"""更改主要外键

Revision ID: 82f230e18db6
Revises: 
Create Date: 2020-01-26 21:00:03.312533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f230e18db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('handler_name', sa.String(length=256), nullable=True),
    sa.Column('real_name', sa.String(length=256), nullable=False),
    sa.Column('record_status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_lost_found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('about', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('images', sa.String(length=1024), nullable=True),
    sa.Column('claimant_id', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('deal_time', sa.DateTime(), nullable=True),
    sa.Column('fix_top', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('look_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('record_status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['t_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('INDEX_LF', 't_lost_found', ['title', 'category_id'], unique=False)
    op.create_table('t_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('fix_top', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_found_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lost_found_id'], ['t_lost_found.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_comment_lost_found_id'), 't_comment', ['lost_found_id'], unique=False)
    op.create_index(op.f('ix_t_comment_user_id'), 't_comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_comment_user_id'), table_name='t_comment')
    op.drop_index(op.f('ix_t_comment_lost_found_id'), table_name='t_comment')
    op.drop_table('t_comment')
    op.drop_table('t_notice')
    op.drop_index('INDEX_LF', table_name='t_lost_found')
    op.drop_table('t_lost_found')
    op.drop_table('t_feedback')
    # ### end Alembic commands ###
