"""增加表情包支持

Revision ID: 88d9b2c5b364
Revises: 0157c3f72f30
Create Date: 2020-03-21 11:08:36.359292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d9b2c5b364'
down_revision = '0157c3f72f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('INDEX_LF', table_name='t_lost_found')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('INDEX_LF', 't_lost_found', ['title', 'category_id'], unique=False)
    # ### end Alembic commands ###
