"""对部分表加入索引

Revision ID: 90504143ccfd
Revises: 393b0a79dfc0
Create Date: 2020-03-21 17:45:29.158642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90504143ccfd'
down_revision = '393b0a79dfc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_openid_wx_id'), 'openid', ['wx_id'], unique=True)
    op.drop_index('wx_id', table_name='openid')
    op.create_index(op.f('ix_t_category_name'), 't_category', ['name'], unique=True)
    op.drop_index('name', table_name='t_category')
    op.create_index(op.f('ix_t_feedback_user_id'), 't_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_t_report_user_id'), 't_report', ['user_id'], unique=False)
    op.create_index(op.f('ix_t_user_qq'), 't_user', ['qq'], unique=True)
    op.create_index(op.f('ix_t_user_real_name'), 't_user', ['real_name'], unique=False)
    op.create_index(op.f('ix_t_user_username'), 't_user', ['username'], unique=True)
    op.drop_index('qq', table_name='t_user')
    op.drop_index('username', table_name='t_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 't_user', ['username'], unique=True)
    op.create_index('qq', 't_user', ['qq'], unique=True)
    op.drop_index(op.f('ix_t_user_username'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_real_name'), table_name='t_user')
    op.drop_index(op.f('ix_t_user_qq'), table_name='t_user')
    op.drop_index(op.f('ix_t_report_user_id'), table_name='t_report')
    op.drop_index(op.f('ix_t_feedback_user_id'), table_name='t_feedback')
    op.create_index('name', 't_category', ['name'], unique=True)
    op.drop_index(op.f('ix_t_category_name'), table_name='t_category')
    op.create_index('wx_id', 'openid', ['wx_id'], unique=True)
    op.drop_index(op.f('ix_openid_wx_id'), table_name='openid')
    # ### end Alembic commands ###
