"""empty message

Revision ID: a862762b8955
Revises: 
Create Date: 2020-01-22 23:58:03.412912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a862762b8955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('academy', sa.String(length=150), nullable=False),
    sa.Column('class_id', sa.String(length=30), nullable=False),
    sa.Column('major', sa.String(length=50), nullable=False),
    sa.Column('qq', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sex', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('UNIQUE_USER', 't_user', ['username', 'qq'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('UNIQUE_USER', table_name='t_user')
    op.drop_table('t_user')
    # ### end Alembic commands ###
