"""更改字段有效限制

Revision ID: ba5678e0197f
Revises: 0171adcde9b8
Create Date: 2020-03-22 21:48:53.575352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba5678e0197f'
down_revision = '0171adcde9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_report',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_t_report_user_id'), 't_report', ['user_id'], unique=False)
    op.alter_column('t_user', 'class_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=35),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('t_user', 'username',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'username',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('t_user', 'real_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('t_user', 'qq',
               existing_type=sa.String(length=12),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('t_user', 'major',
               existing_type=sa.String(length=35),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('t_user', 'class_name',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_t_report_user_id'), table_name='t_report')
    op.drop_table('t_report')
    # ### end Alembic commands ###
