"""增加表情包支持

Revision ID: bebaec67b65e
Revises: af3713e9e7fd
Create Date: 2020-03-21 13:45:22.596253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bebaec67b65e'
down_revision = 'af3713e9e7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_t_lost_found_about'), 't_lost_found', ['about'], unique=False)
    op.create_index(op.f('ix_t_lost_found_category_id'), 't_lost_found', ['category_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_title'), 't_lost_found', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_lost_found_title'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_category_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_about'), table_name='t_lost_found')
    # ### end Alembic commands ###
