"""empty message

Revision ID: d76a8cdd8ace
Revises: 15458a117dce
Create Date: 2020-01-23 14:03:55.176447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd76a8cdd8ace'
down_revision = '15458a117dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('t_user', sa.Column('pasword', sa.String(length=128), nullable=False))
    op.drop_column('t_user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('password', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('t_user', 'pasword')
    op.drop_column('t_user', 'password_hash')
    # ### end Alembic commands ###
