"""更改文件字段的长度

Revision ID: e65a29be53cc
Revises: 5cb5a241c91f
Create Date: 2020-02-28 13:36:48.685597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e65a29be53cc'
down_revision = '5cb5a241c91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_report', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_report', sa.Column('file_name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
