"""添加密码散列

Revision ID: eaae1a52cd1b
Revises: d76a8cdd8ace
Create Date: 2020-01-23 14:09:58.346763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaae1a52cd1b'
down_revision = 'd76a8cdd8ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'pasword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('pasword', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
