"""增加表情包支持

Revision ID: f8620c732814
Revises: ea3884128451
Create Date: 2020-03-21 13:40:12.069825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8620c732814'
down_revision = 'ea3884128451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_t_lost_found_about'), 't_lost_found', ['about'], unique=False)
    op.create_index(op.f('ix_t_lost_found_category_id'), 't_lost_found', ['category_id'], unique=False)
    op.create_index(op.f('ix_t_lost_found_title'), 't_lost_found', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_lost_found_title'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_category_id'), table_name='t_lost_found')
    op.drop_index(op.f('ix_t_lost_found_about'), table_name='t_lost_found')
    # ### end Alembic commands ###
