"""更改反馈类

Revision ID: 6a14caf8b438
Revises: f5c89bc771c0
Create Date: 2020-01-28 20:49:28.952895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a14caf8b438'
down_revision = 'f5c89bc771c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_feedback', sa.Column('handler_time', sa.DateTime(), nullable=True))
    op.drop_column('t_feedback', 'handler_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_feedback', sa.Column('handler_name', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('t_feedback', 'handler_time')
    # ### end Alembic commands ###
